name: Develop
on:
  push:
    branches:
      - master
  
jobs:
  # scan:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
      
  #     - name: Run security scan
  #       run: echo "Running security scan..."
  build:
    runs-on: ubuntu-latest
    # needs: scan 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build project
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python_cicd -f docker/Dockerfile .
    
      - name: docker login
        run: |
          echo ${{ secrets.DOCKER_TOKEN }}  | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/python_cicd:latest